use Migohood;
insert into category(name,code,languaje) value("Space",1,"EN"),("Workspace",2,"EN"),("Parking Space",3,"EN"),("Service",4,"EN"),("Espacio",1,"ES"),("Espacio_de_Trabajo",2,"ES"),("Plaza_de_Aparcamiento",3,"ES"),("Servicio",4,"ES");
insert into type(name,category_id,code,languaje) values("Apartament",1,1,"EN"),("House",1,2,"EN"),("B&B",1,3,"EN"),("Room",1,4,"EN"),("Other",1,5,"EN"),("Apartamento",1,1,"ES"),("Casa",1,2,"ES"),("Cama_y_Desayuno",1,3,"ES"),("Habitacion",1,4,"ES"),("Otros",1,5,"ES");
insert into type(name,category_id,code,languaje) values("Bussiness_Center",2,1,"EN"),("Corporate_Office",2,2,"EN"),("Coworking_Space",2,3,"EN"),("Other_Workspace",2,4,"EN"),("Centro_de_Negocio",2,1,"ES"),("Oficina_Corporativa",2,2,"ES"),("Espacio_de_Trabajo",2,3,"ES"),("Otros_Espacios",2,4,"ES");
insert into type(name,category_id,code,languaje) values("Driveway",3,1,"EN"),("Garage",3,2,"EN"),("Car Park",3,3,"EN"),("Other",3,4,"EN"),("Entrada_de_Coche",3,1,"ES"),("Garaje",3,2,"ES"),("Estacionamiento",3,3,"ES"),("Otros",3,4,"ES");
insert into type(name,category_id,code,languaje) values("Tourism",4,1,"EN"),("Educational",4,2,"EN"),("Cultural",4,3,"EN"),("Recreational",4,4,"EN"),("Eco",4,5,"EN"),("Adventure",4,6,"EN"),("Fitness",4,7,"EN"),("Turismo",4,1,"ES"),("Educacion",4,2,"ES"),("Cultura",4,3,"ES"),("Recreativo",4,4,"ES"),("Eco",4,5,"ES"),("Aventura",4,6,"ES"),("Aptitud",4,7,"ES");
insert into accommodation(name,code,languaje)values("Entire",1,"EN"),("Private",2,"EN"),("Share",3,"EN"),("Todo",1,"ES"),("Privado",2,"ES"),("Compartir",3,"ES");
insert into payment(type,code,languaje)values("Flex",1,"EN"),("Moderate",2,"EN"),("Esctric",3,"EN"),("Flexible",1,"ES"),("Moderado",2,"ES"),("Estricto",3,"ES");
insert into calendar(day,code,languaje) value("All_Days",1,"EN"),("Sunday",2,"EN"),("Monday",3,"EN"),("Tuesday",3,"EN"),("Wednesday",4,"EN"),("Thursday",5,"EN"),("Friday",6,"EN"),("Saturday",7,"EN"),
("Todos_los_Dias",1,"ES"),("Domigo",2,"ES"),("Lunes",3,"ES"),("Martes",3,"ES"),("Miercoles",4,"EN"),("Jueves",5,"ES"),("Viernes",6,"ES"),("Sabado",7,"ES");
insert into duration(type,code,languaje) values("Minute",1,"EN"),("Hour",2,"EN"),("Week",3,"EN"),("Month",4,"EN"),("Minuto",1,"ES"),("Hora",2,"ES"),("Semana",3,"ES"),("Mes",4,"ES");
insert into type_number(type,code,languaje)values("Fixed",1,"EN"),("Cell",2,"EN"),("Fijo",1,"ES"),("Celular",2,"ES");
insert into description(type,description)values("Title","his item is used to specify the title of the service"),("Address1","First address of the service"),("Address2","
Second address of the service"),("Desc_Neighborhood","Neighborhood description"),("Desc_Surroundings","Surroundings description"),("desc_length","Length for google map"),("desc_latitud","Latitud for google map"),("description","service description"),("crib","crib description"),("guest access","User access description"),("socialize","check the socialize"),("available","check the available"),("desc_guest","guest description"),("desc_note","Any note you want to leave");
insert into house_rules(type)values("Apto para niños(2 a 12 años)"),("Apto para bebes(0 a 2 años)"),("Se Admiten Mascotas"),("Permitido Fumar"),("Eventos fiestas permitidos"),("Otras reglas"),("Telefono de Invitados"),("Correo de Invitados"),("Perfil de Invitados"),("Pago de Invitados"),("Invitado Previsto"),("Recomendacion de Invitado"),("Instruccion"),("Nombre Wifi"),("contraseña Wifi");
insert into bed(type,code,languaje)values("Double",1,"EN"),("Queen",2,"EN"),("Individual",3,"EN"),("Sofa",4,"EN"),("Other",5,"EN"),
("Doble",1,"ES"),("Reina",2,"ES"),("Individual",3,"ES"),("Sofa",4,"ES"),("Otro",5,"ES");
insert into type_amenities(name,code,languaje)values("Amenities",1,"EN"),("Your_offer",2,"EN"),("Guest_use",3,"EN"),("Comodidades",1,"ES"),("Tu Oferta",2,"ES"),("Uso de los huesped",3,"ES");
-- ingles--
insert into amenities(name,category_id,type_amenities_id,languaje,code)values("pets_allowed",1,1,"EN",1),("events_allowed",1,1,"EN",2),("production_allowed",1,1,"EN",3),("family_friendly",1,1,"EN",4),("business_guests",1,1,"EN",5),("smoke_free",1,1,"EN",6),("gym",1,1,"EN",7),("parking",1,1,"EN",8);
insert into amenities(name,category_id,type_amenities_id,languaje,code)values("essential",1,2,"EN",9),("shampoo",1,2,"EN",10),("wifi",1,2,"EN",11),("tv",1,2,"EN",12);
insert into amenities(name,category_id,type_amenities_id,languaje,code)values("kitchen",1,3,"EN",13),("laundry_washer",1,3,"EN",14),("laundry_dryer",1,3,"EN",15),("hot_tub",1,3,"EN",16),("parking",1,3,"EN",17),("elevator",1,3,"EN",18),("pool",1,3,"EN",19),("gym",1,3,"EN",20);
-- español--
insert into amenities(name,category_id,type_amenities_id,languaje,code)values("mascotas_permitidas",1,1,"ES",1),("eventos_permitida",1,1,"ES",2),("produccion_permitida",1,1,"ES",3),("familia_amable",1,1,"ES",4),("cliente_negocio",1,1,"ES",5),("libre_de_humo",1,1,"ES",6),("gimnasio",1,1,"ES",7),("estacionamiento",1,1,"ES",8);
insert into amenities(name,category_id,type_amenities_id,languaje,code)values("esencial",1,2,"ES",9),("champu",1,2,"ES",10),("wifi",1,2,"ES",11),("television",1,2,"ES",12);
insert into amenities(name,category_id,type_amenities_id,languaje,code)values("cocina",1,3,"ES",13),("lavadero",1,3,"ES",14),("secadora",1,3,"ES",15),("tina_caliente",1,3,"ES",16),("estacionamiento",1,3,"ES",17),("ascensor",1,3,"ES",18),("piscina",1,3,"ES",19),("gimnasio",1,3,"ES",20);
