 use migohood;
insert into category(name) value("Space"),("Workspace"),("Parking Space"),("Service");
insert into type(name,category_id) values("Apartament",1),("House",1),("B&B",1),("Room",1),("Other",1);
insert into type(name,category_id) values("Bussiness Center",2),("Corporate Office",2),("Coworking Space",2),("Other Workspace",2);
insert into type(name,category_id) values("Driveway",3),("Garage",3),("Car Park",3),("Other",3);
insert into type(name,category_id) values("Tourism",4),("Educational",4),("Cultural",4),("Recreational",4),("Eco",4),("Adventure",4),("Fitness",4);
insert into amenities(name,category_id)value("Pets Allowed",1),("Events Allowed",1),("Production (Video or Photography) Allowed",1),("Family Friendly",1),("Business Guest",1),("Smoke free",1),("Gym",1),("Parking",1);
insert into amenities(name,category_id) values("Wifi",2),("Pets Allowed",2),("Events Allowed.",2),("Production (Video or Photography) Allowed",2),("Smoke free",2),("Gym",2),("Parking",2);
insert into accommodation(name)values("private"),("Share");
insert into calendar(day) value("All Days"),("Sunday"),("Monday"),("Tuesday"),("Wednesday"),("Thursday"),("Friday"),("Sturday");
insert into duration(type) values("Minute"),("Hour"),("Week"),("Month");
insert into type_number(type)values("Fixed"),("Cell");
insert into description(type)values("title"),("address1"),("address2"),("des_neighborhood"),("desc_surroundings"),("desc_length"),("desc_latitud"),("description"),("apt"),("desc_around");
insert into house_rules(type)values("Apto para niños(2 a 12 años)"),("Apto para bebes(0 a 2 años)"),("Se Admiten Mascotas"),("Permitido Fumar"),("Eventos fiestas permitidos");