use Migohood;
insert into languaje(id,name)
VALUES ('1','Chino')
,('2','Arabe')
,('3','Bielorruso')
,('4','Bulgaria')
,('5','Catalán')
,('6','Checo')
,('7','Danés')
,('8','Alemán')
,('9','Griego')
,('10','Inglés')
,('11','Español')
,('12','Estonia')
,('13','Finlandia')
,('14','Francés')
,('15','Irlandés')
,('16','India')
,('17', 'Croata') 
,('18','Húngaro')
,('19','Indonesio')
,('20','Islandés')
,('21','Italiano')
,('22','Hebreo')
,('23','Japonés')
,('25','Coreano')
,('26','Lituano')
,('27','Letón')
,('28','Macedonio')
,('29','Malayo')
,('30','Maltés')
,('31','Neerlandés [Bélgica]')
,('32','Neerlandés [Holanda]')
,('33','Noruego')
,('34','Polaco')
,('35','Portugués')
,('36','Rumano')
,('37','Ruso')
,('38','Eslovaco')
,('39','Albanés')
,('40','Serbio')
,('41','Sueco')
,('42','Tailandés')
,('43','Turco [Turquía]')
,('44','Ucranio')
,('45','Vietnamita')
,('46','Chino');